{% set name = "pyprecice" %}
{% set version = "2.4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyprecice-{{ version }}.tar.gz
  sha256: f89c47a78991f0e558b3b9a38b13746777380d45cb5ca58c3ba8c4d0cb88274e

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - packaging
    - pip
    - precice
    - python
  run:
    - mpi4py
    - numpy
    - python

test:
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - python -c "import precice"
    - pip check
  requires:
    - pip

about:
  home: https://precice.org
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python language bindings for preCICE
  description: |
    This package provides python language bindings for the C++ library 
    preCICE. 
  doc_url: https://precice.org/installation-bindings-python.html
  dev_url: https://github.com/precice/python-bindings

extra:
  recipe-maintainers:
    - IshaanDesai
    - jan-janssen
