{% set name = "pyprecice" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyprecice-{{ version }}.tar.gz
  sha256: 2fe8582fa3d27b42d995f5695721d01424a36874b5bd439ae776e84262283d94

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - packaging
    - setuptools
    - pip
    - precice
    - python
    - pkgconfig
  run:
    - mpi4py
    - numpy
    - python
    - cython

test:
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - python -c "import precice"
    - pip check
  requires:
    - pip

about:
  home: https://precice.org
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python language bindings for preCICE
  description: |
    This package provides python language bindings for the C++ library 
    preCICE. 
  doc_url: https://precice.org/installation-bindings-python.html
  dev_url: https://github.com/precice/python-bindings

extra:
  recipe-maintainers:
    - IshaanDesai
    - jan-janssen
